# Generated by Django 3.0.5 on 2021-02-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210211_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
